import image1 from '/src/assets/background/bosque1.jpg';

let filterDateHeight1 = [
  {id:1,
    country: 'Perú',
    image: image1,
    title: 'UM Piedra Iman (Open Pit)',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
  {id:2,
    country: 'Perú',
    image: image1,
    title: 'UM Piedra Iman (Subterráneo)',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
  {id:3,
    country: 'Perú',
    image: image1,
    title: 'UM Santa Rosa',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
  {id:4,
    country: 'Perú',
    image: image1,
    title: 'UM Shuntur',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
  {id:5,
    country: 'Perú',
    image: image1,
    title: 'UM Suyubamba',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
  {id:6,
    country: 'Bolivia',
    image: image1,
    title: 'UM Piedra Iman',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
  {id:7,
    country: 'Bolivia',
    image: image1,
    title: 'Tunel Incahuasi',
    description: 'La Paz Bolivia',
    text: 'My first iOS app is available on the AppStore. I literally didn’t know anything about SwiftUI (still not much) and in probably 4 weeks was able to recreate my android app for iOS. Highly recommend MengTo videos!',
    msnm: 0},
]

export default dataProyectHeight;